version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: edu-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2201
      POSTGRES_DB: education
    ports:
      - "5434:5433"
